export const GET_TOOLS_SUCCESS = 'GET_TOOLS_SUCCESS'
export const GET_TOOLS_ERROR = 'GET_TOOLS_ERROR'

export const DELETE_TOOLS_SUCCESS = 'DELETE_TOOLS_SUCCESS'
export const DELETE_TOOLS_ERROR = 'DELETE_TOOLS_ERROR'

export const ADD_TOOLS_SUCCESS = 'ADD_TOOLS_SUCCESS'
export const ADD_TOOLS_ERROR = 'ADD_TOOLS_ERROR'
